version: 0.2

phases:
  pre_build:
    commands:
      - "echo Logging in to Amazon ECR..."
      - "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 135808923997.dkr.ecr.us-east-1.amazonaws.com"
      - "echo Logging in to Docker Hub..."
      - "docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD"
      - "REPOSITORY_URI=135808923997.dkr.ecr.us-east-1.amazonaws.com/shs-streamlit-app"
      - "IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)"
  build:
    commands:
      - "echo Build started on $(date)"
      - "echo Building the Docker image..."
      - "docker build -t $REPOSITORY_URI:$IMAGE_TAG ."
  post_build:
    commands:
      - "echo Build completed on $(date)"
      - "echo Pushing the Docker image..."
      - "docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest"
      - "docker push $REPOSITORY_URI:$IMAGE_TAG"
      - "docker push $REPOSITORY_URI:latest"
artifacts:
  files:
    - "**/*"
